require([
    "js/plugins/bootstrap-datepicker/bootstrap-datepicker.js",
    "js/plugins/bootstrap-maxlength/bootstrap-maxlength.js",
    "js/plugins/bootstrap-multiselect/bootstrap-multiselect.js",
    "js/plugins/bootstrap-timepicker/bootstrap-timepicker.min.js",
    "js/plugins/bootstrap-tokenfield/bootstrap-tokenfield.min.js",
    "js/plugins/bootstrap-tokenfield/scrollspy.js",
    "js/plugins/bootstrap-tokenfield/affix.js",
    "js/plugins/bootstrap-tokenfield/typeahead.min.js",
    "js/plugins/datatables/jquery.dataTables.js",
    "js/plugins/datatables/datatables-bs3.js",
    "js/plugins/daterangepicker/moment.js",
    "js/plugins/daterangepicker/daterangepicker.js",
    "js/plugins/dropzone/dropzone.js",
    "js/plugins/easypiechart/jquery.easypiechart.min.js",
    "js/plugins/flot/jquery.flot.resize.js",
    "js/plugins/flot/jquery.flot.tooltip.min.js",
    "js/plugins/flot/jquery.flot.pie.js",
    "js/plugins/fullcalendar/fullcalendar.min.js",
    "js/plugins/hisrc/hisrc.js",
    "js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js",
    "js/plugins/jvectormap/maps/jquery-jvectormap-world-mill-en.js",
    "js/plugins/ladda/spin.min.js",
    "js/plugins/ladda/spin.js",
    "js/plugins/ladda/ladda.min.js",
    "js/plugins/messenger/messenger.min.js",
    "js/plugins/messenger/messenger-theme-flat.js",
    "js/plugins/moment/moment.min.js",
    "js/plugins/morris/morris.js",
    "js/plugins/morris/raphael-2.1.0.min.js",
    "js/plugins/slimscroll/jquery.slimscroll.min.js",
    "js/plugins/sparkline/jquery.sparkline.min.js",
    "js/plugins/summernote/summernote.min.js",
    "js/plugins/validate/jquery.validate.min.js",
    "js/plugins/flot/flot-demo-data.js",
    "js/demo/calendar-demo.js",
    "js/demo/dashboard-demo.js",
    "js/demo/sliders-demo.js",
    "js/demo/map-demo-data.js",
    "js/demo/advanced-form-demo.js",
    "js/demo/mailbox-demo.js"
], function(file, file2, file3, file4, file5, file6, file7, file8, file9, file10, file11, file12, file13, file14, file15, file16, file17, file18, file19, file20, file21, file22, file23, file24, file25, file26, file27, file28, file29, file30, file31, file32, file33, file34, file35, file36, file37, file38, file39, file40) {
    //This function is called when scripts/helper/util.js is loaded.
    //If util.js calls define(), then this function is not fired until
    //util's dependencies have loaded, and the util argument will hold
    //the module value for "helper/util".
});
